### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by pgporada** [erikvanbrakel/terraform-provider-sumologic#10]
Can you show some examples of using this provider with resources?

**Comment by erikvanbrakel** [comment]
```
provider "sumologic" {
    access_id = ""
    access_key = ""
    environment = "" # your region (eu, us, etc.)
}

resource "sumologic_collector" "collector" {
    name = ""
    description = ""
    category = ""
}

resource "sumologic_http_source" "http" {
    name = "" # string
    messagePerRequest = "" # bool
    collector_id = "${sumologic_collector.collector.id}"
}
```

That should work. I'm mainly waiting for Terraform to implement some way to deal with sensitive values so I can add more sources (the polling source comes to mind). 
I'm not using this myself yet, so I can't really say if it really works (it works in my local tests). Let me know if it's useful to you, that'll give me some incentive to pour some more time into it! :-)

**Comment by erikvanbrakel** [comment]
How-to is in README.md now.
