### ISSUE TITLE
permission denied / file does not exist

### ISSUE THREAD

**Issue by shinitiandrei** [erikvanbrakel/terraform-provider-sumologic#18]
Hi! 
Sorry if this is considered a silly question since I'm a bit new to Terraform, but I've been cracking my head with this for a while so...
I followed your tutorial step by step, word by word and I tried in both Windows and Ubuntu.
In both cases when I try to run "terraform plan" I'm always getting this error message:
Ubuntu: **`provider.sumologic: fork/exec /github/terraform/terraform-provider-sumologic: permission denied`**  
(+ I tried moving the .terraformrc file to terraform's folder and my project's folder)
Windows: **`provider.sumologic: exec: "C:\\HashiCorp\\Terraform\\terraform-provider-sumologic": file does not exist`**
_In Ubuntu I've granted 777 permission to the folder & files and still same_
My code is basically one terraform file as you see below:
`provider "aws" {
  access_key = {my-access-key}
  secret_key = {my secret key}
  region     = "us-west-2"
}

resource "aws_instance" "sumologic_terraform" {
  ami           = "ami-db6bf3bb"
  instance_type = "t2.micro"
}

provider "sumologic" {
    access_id =  {my-access-id}
    access_key =  {my-access-key}
    environment = "us-west-2"
}

resource "sumologic_collector" "collector" {
    name = "redhat_collector"
    description = "redhat generated by terraform with sumo"
    category = "collector-container"
}`
Is there any other documentation that I should follow? I read this https://www.terraform.io/docs/plugins/basics.html but it didn't work as well...
If I got it wrong, really sorry about that, otherwise can you update your documentation with more details? 
Thank you!

**Comment by erikvanbrakel** [comment]
Firstly, I agree, docs need to be better.

I'm using this myself on both windows and ubuntu. I'm cheating a bit on windows, as I just placed the binary next to the main terraform.exe which works without any config files.
On ubuntu, I write `.terraformrc` to my home directory, with this content:

```hcl
providers {
  sumologic = "/full/path/to/terraform-provider-sumologic"
}
```

So in short, putting the `terraform-provider-sumologic` binary next to your terraform binary should work. On ubuntu, write `.terraformrc` to your home-dir with the providers block as above. On windows I believe it looks for `.terraformrc` in %APPDATA%. 

And yes, on linux it's required to make the binary executable.

**Comment by erikvanbrakel** [comment]
@shinitiandrei did you get it to work?

**Comment by shinitiandrei** [comment]
Hi! @erikvanbrakel 
Sorry, I couldn't test it yet, I will try tomorrow at my office, but as far as I remember I also tried this and didn't work as well...
I will send you more details about my environment and how I'm doing it
Thank you!!

**Comment by shinitiandrei** [comment]
So I basically downloaded the binary from Terraform (https://www.terraform.io/downloads.html) then I added to my Environment Variables for both Windows and Ubuntu.
Then I cloned your project just beside my terraform.exe in windows and same in ubuntu...
_Ubuntu: /opt/terraform/terraform-provider-sumologic
Windows: C:\HashiCorp\Terraform\terraform-provider-sumologic_

In Windows as you said, I didn't provide any .terraformrc and it looks for the right path. But I also tried to add .terraformrc and seems not to work though..
In Ubuntu, I added .terraformrc in my project path (/github/terraform/.terraformrc) and added:
`providers {
  sumologic = "/opt/terraform/terraform-provider-sumologic"
}`
Plus I made the binary executable, as you can see the output below:
```
root@andrei-soltius:/opt/terraform/terraform-provider-sumologic# ls -lsa
total 52
4 drwxrwxrwx 7 root root 4096 May  5 10:24 .
4 drwxrwxrwx 3 root root 4096 May  8 12:55 ..
4 drwxrwxrwx 2 root root 4096 May  5 10:24 build
4 drwxrwxrwx 8 root root 4096 May  5 10:24 .git
4 -rwxrwxrwx 1 root root  283 May  5 10:24 .gitignore
4 drwxrwxrwx 2 root root 4096 May  5 10:24 go-sumologic
4 -rwxrwxrwx 1 root root 1072 May  5 10:24 LICENSE
4 -rwxrwxrwx 1 root root  234 May  5 10:24 main.go
4 drwxrwxrwx 2 root root 4096 May  5 10:24 provider
4 -rwxrwxrwx 1 root root 1583 May  5 10:24 Rakefile
4 -rwxrwxrwx 1 root root 2658 May  5 10:24 README.md
4 -rwxrwxrwx 1 root root  332 May  5 10:24 .travis.yml
4 drwxrwxrwx 3 root root 4096 May  5 10:24 vendor
```
Then, I go to my project's directory and run the command: **terraform plan** 
it returns the message that I have previously posted.

**Comment by erikvanbrakel** [comment]
Did you try placing the _binary_ files next to your terraform executable? You can download those here: https://github.com/erikvanbrakel/terraform-provider-sumologic/releases. I don't think you can just point to the sources.

**Comment by shinitiandrei** [comment]
ohhh now I see! 
Now both are working @erikvanbrakel! Thank you for your wonderful and quick support! 
I would just like to ask you to improve your docs then, as it doesn't say specifically to download your project as a binary:

> Provider init

> Place terraform-provider-sumologic in the same **_directory as terraform binary_** or add a .terraformrc file with the provider stanza:
> 
> providers {
>   sumologic = "/PATH/TO/MODULE/ARCH/terraform-provider-sumologic"
> }

In my perspective, I just needed to "clone" your repository and refer it somewhere...I interpreted as just terraform binary, and not your project as binary...
Sorry for my inconvenience here though...So just add this detail in your docs please, would help some new people as helped me :)
Thanks heaps!!

**Comment by erikvanbrakel** [comment]
Thanks for the feedback :-) Keep in mind when using the plugin that you might run into some sharp edges, as it's not very polished at the moment. Please drop any bugs and feature requests in this repo as an issue and I'll see what I can do :-)
