### ISSUE TITLE
Publish to Module Registry

### ISSUE THREAD

**Issue by josacar** [erikvanbrakel/terraform-provider-sumologic#33]
Add provider to Terraform Module Registry

https://www.hashicorp.com/blog/hashicorp-terraform-module-registry/

**Comment by erikvanbrakel** [comment]
I believe the registry is not for providers, but for modules (e.g. an RDS module which sets up an AWS RDS instance with certain settings).

**Comment by josacar** [comment]
Ok. my bad reading it.
