### ISSUE TITLE
API rate limit for this user has been exceeded.

### ISSUE THREAD

**Issue by yelvert** [erikvanbrakel/terraform-provider-sumologic#35]
There needs to be a built in workaround for API rate limits, maybe adding a `max_retries` to the provider like the AWS provider offers, https://www.terraform.io/docs/providers/aws/#max_retries

**Comment by erikvanbrakel** [comment]
Sumologic recently released their own, officially supported provider. As such, I am not actively maintaining this one. Their efforts can be found on their github pages: https://github.com/SumoLogic/sumologic-terraform-provider
