### ISSUE TITLE
Issue refreshing state when deleting sumologic module

### ISSUE THREAD

**Issue by mwarkentin** [erikvanbrakel/terraform-provider-sumologic#37]
Hey there, I was experimenting with this provider inside of a module and ran into an issue when trying to remove the module I had instantiated. The error was not very clear:

```
Error refreshing state: 1 error(s) occurred:

* module.sumologic.sumologic_collector.cloudformation: sumologic_collector.cloudformation:
```

The module itself is quite simple:

`main.tf`

```
provider "sumologic" {
  environment = "${var.sumologic_environment}"
}

resource "sumologic_collector" "cloudformation" {
  name        = "${var.environment}-cloudformation"
  description = "Cloudformation logs for ${var.environment}"
}

resource "sumologic_http_source" "cloudformation" {
  name         = "HTTP"
  category     = "aws/cloudformation"
  collector_id = "${sumologic_collector.cloudformation.id}"

  # SumoLogic lambda batches messages into a single request
  messagePerRequest = "false"
}
```

`outputs.tf`

```
output "cloudformation_http_url" {
  description = "URL for the sumologic cloudformation http endpoint."

  value = "${sumologic_http_source.cloudformation.url}"
}
```

`variables.tf`

```
variable "environment" {
  description = "The environment name"
}

variable "sumologic_environment" {
  description = "The sumologic API endpoint to use. Default is us2."

  default = "us2"
}

```

I was eventually able to clean it up by removing the two resources defined inside the module from the module, plan + apply, and then remove the module instantiation. Any idea if there's an issue with the provider or possibly how I was using it?

**Comment by erikvanbrakel** [comment]
Hi @mwarkentin, which version of Terraform are you using, and which version of the provider?

**Comment by mwarkentin** [comment]
Sorry, that would've probably been useful info to include. 😄 

Terraform: `0.10.7`
Sumo provider: `0.3.0`

**Comment by erikvanbrakel** [comment]
Apologies for the late response. I didn't manage to reproduce this using the versions you specified. I tried these scenarios, using your module files and a `main.tf` which references it:

```hcl
module "sumo_module" {
  source = "./module"
  environment = "dev"
}
```

1. `terraform apply`
2. `terraform destroy`

This worked for me.

1. `terraform apply`
2. Remove module from root (basically, empty `main.tf`)
3. `terraform apply`

Can you give some more info?

**Comment by mwarkentin** [comment]
Were you using the same version of terraform? Possibly an issue that they’ve fixed now?

**Comment by erikvanbrakel** [comment]
I used terraform `0.10.7` as you specified. Can you reproduce it with full debug logs? You can enable this by setting the `TF_LOG` environment variable to `debug` and `TF_LOG_PATH` to the file path you want to write it to.

On another note, which OS are you using? I can't imagine why, but maybe it's related.

**Comment by mwarkentin** [comment]
I'm on OSX, using terraform installed via tfenv. I'll see if I can reproduce again and provide some more details.

**Comment by erikvanbrakel** [comment]
Sumologic recently released their own, officially supported provider. As such, I am not actively maintaining this one. Their efforts can be found on their github pages: https://github.com/SumoLogic/sumologic-terraform-provider
