### ISSUE TITLE
exits without any error

### ISSUE THREAD

**Issue by niroliyanage** [erikvanbrakel/terraform-provider-sumologic#43]
The plan goes without an issue , but when trying to apply it just dies without any exception

{code}
Error: Error applying plan:

1 error(s) occurred:

* module.cluster_bootstrap.sumologic_collector.collector: 1 error(s) occurred:

* sumologic_collector.collector:

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
{code}

config is pretty standard as per the readme

Thanks
NIro

**Comment by erikvanbrakel** [comment]
Sumologic recently released their own, officially supported provider. As such, I am not actively maintaining this one. Their efforts can be found on their github pages: https://github.com/SumoLogic/sumologic-terraform-provider
